import React from 'react'
const C={midnight:'#0E1B2E',brand:'#2A6AF4',teal:'#00796B',neutral:'#475569',cloud:'#F5F7FA',white:'#FFFFFF'}
function BrandIcon({size=28,stroke=3,color=C.brand}){return(<svg width={size} height={size} viewBox='0 0 64 64' aria-hidden><path d='M24 12 L12 32 L24 52' fill='none' stroke={color} strokeWidth={stroke} strokeLinecap='round' strokeLinejoin='round'/><path d='M40 12 L52 32 L40 52' fill='none' stroke={color} strokeWidth={stroke} strokeLinecap='round' strokeLinejoin='round'/></svg>)}
function Icon({name,size=20,color=C.brand}){const p={fill:'none',stroke:color,strokeWidth:2,strokeLinecap:'round',strokeLinejoin:'round'}; if(name==='cloud')return(<svg width={size} height={size} viewBox='0 0 24 24'><path {...p} d='M20 17.5a3.5 3.5 0 0 0-3.5-3.5h-.5a5 5 0 0 0-9.7-1.5A3 3 0 0 0 6 19h10.5A3.5 3.5 0 0 0 20 17.5z'/></svg>); if(name==='mail')return(<svg width={size} height={size} viewBox='0 0 24 24'><path {...p} d='M4 6h16v12H4z'/><path {...p} d='m22 6-10 7L2 6'/></svg>); if(name==='server')return(<svg width={size} height={size} viewBox='0 0 24 24'><rect {...p} x='3' y='4' width='18' height='6' rx='2'/><rect {...p} x='3' y='14' width='18' height='6' rx='2'/><path {...p} d='M7 8h.01M7 18h.01'/></svg>); if(name==='stack')return(<svg width={size} height={size} viewBox='0 0 24 24'><path {...p} d='m12 2 9 5-9 5-9-5 9-5z'/><path {...p} d='m3 12 9 5 9-5'/><path {...p} d='m3 17 9 5 9-5'/></svg>); return null}
export default function App(){return(<div style={{background:C.cloud,color:C.neutral}}>
<header className='sticky'><div className='container' style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'16px 24px'}}><div style={{display:'flex',alignItems:'center',gap:10}}><BrandIcon/><span style={{fontWeight:800,fontSize:18}}>moliseke</span></div><nav aria-label='Primary'><a href='#services'>Services</a><a href='#why'>Why us</a><a href='#approach'>Approach</a><a href='#regions'>Regions</a><a href='#contact'>Contact</a></nav><a href='mailto:info@moliseke.com' className='btn btn-primary'>Contact</a></div></header>
<section><div className='container' style={{padding:'64px 24px'}}><div style={{background:C.midnight,color:'#fff',borderRadius:24,padding:'40px 32px',position:'relative',boxShadow:'0 24px 40px rgba(2,6,23,.2)'}}><h1 style={{fontFamily:'Manrope,Inter,Arial,sans-serif',fontSize:48,lineHeight:1.1,fontWeight:800}}>Cloud migrations & email moves for SMBs</h1><p style={{marginTop:12,opacity:.92,maxWidth:740}}>On-prem → Azure & AWS • Microsoft 365 / Google Workspace • Terraform deployments. We work across the US, Canada, UK, EU & Australia.</p><div style={{marginTop:18,display:'flex',gap:12,flexWrap:'wrap'}}><a href='#services' className='btn btn-primary'>Our services</a><a href='#contact' className='btn btn-outline'>Get in touch</a></div><div aria-hidden style={{position:'absolute',right:24,bottom:-24,opacity:.08,transform:'scale(2)'}}><BrandIcon size={120} stroke={8} color='#fff'/></div></div></div></section>
<section id='services' style={{padding:'48px 0'}}><div className='container'><h2 style={{fontFamily:'Manrope,Inter,Arial,sans-serif',fontWeight:800,color:C.midnight}}>Services</h2><div style={{display:'grid',gridTemplateColumns:'1fr',gap:16,marginTop:12}}><div className='card'><div style={{display:'flex',alignItems:'center',gap:10}}><Icon name='cloud'/><h3>On-prem → Azure & AWS migrations</h3></div><ul><li>• Discovery & readiness assessment</li><li>• Architecture & landing zone setup</li><li>• Cutover with rollback plan</li><li>• Security & compliance baked-in</li></ul></div><div className='card'><div style={{display:'flex',alignItems:'center',gap:10}}><Icon name='stack'/><h3>Email to Microsoft 365 & Google Workspace</h3></div><ul><li>• Domain & DNS alignment</li><li>• Mailbox & data migration (staged/cutover)</li><li>• Security policies: MFA, DKIM, DMARC</li><li>• End-user enablement & support</li></ul></div><div className='card'><div style={{display:'flex',alignItems:'center',gap:10}}><Icon name='server'/><h3>Infrastructure deployments with Terraform</h3></div><ul><li>• IaC standards for Azure & AWS</li><li>• CI/CD pipelines & environments</li><li>• Observability & cost guardrails</li><li>• Documentation & handover</li></ul></div></div></div></section>
<section id='why' style={{padding:'48px 0',background:'#fff'}}><div className='container'><h2 style={{fontFamily:'Manrope,Inter,Arial,sans-serif',fontWeight:800,color:C.midnight}}>Why moliseke</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:12,marginTop:12}}><div className='card'><strong>Clarity over complexity</strong><p style={{marginTop:6}}>Readable runbooks, diagrams and status. We make cloud changes transparent.</p></div><div className='card'><strong>Security by design</strong><p style={{marginTop:6}}>MFA, least privilege and audit baked-in from day one—no surprises later.</p></div><div className='card'><strong>Measurable outcomes</strong><p style={{marginTop:6}}>Cutover windows, rollback points and KPI dashboards to prove value.</p></div></div></div></section>
<section id='approach' style={{padding:'48px 0'}}><div className='container'><h2 style={{fontFamily:'Manrope,Inter,Arial,sans-serif',fontWeight:800,color:C.midnight}}>Our approach</h2><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:12,marginTop:12}}>{[{step:'Discover',desc:'Inventory, risks, success criteria'},{step:'Plan',desc:'Architecture, timeline, runbook'},{step:'Migrate',desc:'Pilot, iterate, cutover'},{step:'Harden',desc:'Security, backups, DR'},{step:'Operate',desc:'Docs, handover, support'}].map((s,i)=>(<div key={s.step} className='card'><div style={{color:C.teal,fontWeight:700,fontSize:12}}>{String(i+1).padStart(2,'0')}</div><div style={{fontWeight:700}}>{s.step}</div><div style={{fontSize:14,opacity:.8}}>{s.desc}</div></div>))}</div></div></section>
<section id='regions' style={{padding:'48px 0'}}><div className='container'><h2 style={{fontFamily:'Manrope,Inter,Arial,sans-serif',fontWeight:800,color:C.midnight}}>Regions we serve</h2><div style={{display:'flex',flexWrap:'wrap',gap:10,marginTop:10}}>{['United States','Canada','United Kingdom','European Union','Australia'].map(r=><span key={r} className='chip'>{r}</span>)}</div></div></section>
<section id='contact' style={{padding:'48px 0',background:C.midnight,color:'#fff'}}><div className='container'><h2 style={{fontFamily:'Manrope,Inter,Arial,sans-serif',fontWeight:800}}>Let’s talk about your migration</h2><p style={{opacity:.9,maxWidth:720}}>Email us a short note about your current environment and target platform. We’ll reply with a brief plan and timeline options.</p><div style={{marginTop:12,display:'flex',gap:12,flexWrap:'wrap'}}><a href='mailto:info@moliseke.com' className='btn btn-primary'>info@moliseke.com</a><a href='#services' className='btn btn-outline'>Explore services</a></div></div></section>
<footer style={{padding:'16px 0',background:'#fff',borderTop:'1px solid #e5e7eb'}}><div className='container' style={{display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:14}}><div style={{display:'flex',alignItems:'center',gap:8}}><BrandIcon size={18}/><span>moliseke</span></div><div style={{opacity:.7}}>© {new Date().getFullYear()} moliseke — moliseke.com</div></div></footer>
</div>)}
